#! /bin/sh

# autostart
sxhkd &
feh --bg-scale $HOME/Pictures/debian.jpg &
$HOME/.config/bspwm/panel.sh &
killall trayer
trayer --edge top --align right --widthtype request --heighttype pixel --height 20 --transparent true --alpha 240 --distance 310 --distancefrom right --expand &
killall nm-applet
nm-applet &
killall volumeicon
volumeicon &
xsetroot -cursor_name left_ptr &
xrdb -merge $HOME/.Xresources &
killall compton
compton --config $HOME/.config/compton.conf &
xautolock &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config top_padding 22

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^2' follow=on focus=on
