#!/bin/bash

option=$(echo -e " Exit\n Reboot\n ShutDown\n " | dmenu  -fn 'Inconsolata-11')

case $option in
	" Exit" )
		prompt=$(echo -e "No\nYes" | dmenu -fn 'Inconsolata-11' -p 'Exit ')
		[ "$prompt" == "Yes" ] && notify-send "Exiting Window Manager..." && sleep 1s && sudo killall dwm;;
	" Reboot" )
		prompt=$(echo -e "No\nYes" | dmenu -fn 'Inconsolata-11' -p 'Reboot ')
		[ "$prompt" == "Yes" ] && notify-send "System Rebooting..." && sleep 1s && reboot ;;
	" ShutDown" )
		prompt=$(echo -e "No\nYes" | dmenu -fn 'Inconsolata-11' -p 'ShutDown ')
		[ "$prompt" == "Yes" ] && notify-send "System Shutting Down..." && sleep 1s && poweroff ;;
esac
