#!/bin/sh

# selecting the ssid form the list of available networks
ssid=$(nmcli device wifi list | \
	sed "s/^\*\+\s//" | awk {'print $2'} | \
 	sed "/BSSID/d" | dmenu -fn "freemono-10" -l 5 -p "Wifi ")

# if no ssid selected then exit
[ -z "$ssid" ] && exit

# check if already connected to the network
list=$(nmcli connection show | awk {'print $1'})
echo $list | grep $ssid > /dev/null || \
	passwd=$(echo | dmenu -fn "freemono-10" -p "Password ") \

# if not connected to network before then connect with password
[ -n "$passwd" ] && \
	nmcli device wifi connect $ssid password $passwd > /dev/null && \
	notify-send "Connection Established" "You are now connected to $ssid network" && exit

# if already connected to network then connect without password
nmcli device wifi connect $ssid > /dev/null && notify-send "Connection Established" \
 	"You are now connected to $ssid network"

